### ISSUE TITLE
Adding the option to Decrypt a PDF

### ISSUE THREAD

**Issue by jmaleonard** [nisaacson/pdf-extract#14]
Hi,

Currently not able to pass through some form of arguments to pdftk to decrypt a document. 

Id like to submit a change to allow for this.

**Comment by bhaskar20** [comment]
much needed change request

**Comment by nisaacson** [comment]
I am happy to look at a PR

**Comment by jmaleonard** [comment]
Will submit a PR

**Comment by jmaleonard** [comment]
https://github.com/nisaacson/pdf-extract/pull/25/
