### ISSUE TITLE
Timeout in Tests / Complete,Done,Error callback never called OSX

### ISSUE THREAD

**Issue by JBenedettini** [nisaacson/pdf-extract#15]
This package is perfect for what i am trying to do, however i cant seem to get it work on OSX. I dont get any errors when running in my Node application, however it never fires any of its callbacks after the process function. When running the NPM Test from within the node modules, dependencies come back fine, but i get 7 errors after all having to do with Timeout after. Ive upped the Timeouts in the test and still not running. Only diffrence i have is Tesseract being version 3.04.00, however im not even trying to use OCR so i cant image this would be causing the issues. 

Any help is appreciated!

**Comment by nisaacson** [comment]
Can you post some example code that is not working for you? Alternatively if you don't need the OCR support you can look at https://github.com/nisaacson/pdf-text-extract

**Comment by JBenedettini** [comment]
My system specs
OSX: 10.11.1
Node: 4.2.2
pdftk: 2.02
pdftotext: 0.35.0
gs: 9.16
tesseract: 3.04.00

My code running in Node.js is (And test.pdf is a searchable Text PDF)
```javascript
var pdf_extract = require('pdf-extract');
var absolute_path_to_pdf = './public/images/test.pdf';

var options = {
  type: 'text'  // extract the actual text in the pdf file
}

var processor = pdf_extract(absolute_path_to_pdf, options, function(err) {
  if (err) {
  	console.log(err);
    return callback(err);
  }
});
processor.on('complete', function(data) {
  console.log('All Done!');
  callback(null, data.text_pages);
});
processor.on('error', function(err) {
  console.log(err);
  return callback(err);
});

```
However neither function processor.on *error* or *complete* ever get fired.

My NPM Test from the pdf-extract module comes out as so

```
  ✖ 7 of 13 tests failed:

  1) 02 Split Test should split multi-page pdf in single page pdf files:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/User/WebDevelopment/test/pdftest/node_modules/pdf-extract/node_modules/mocha/lib/runnable.js:140:21)
      at Timer.listOnTimeout (timers.js:92:15)

  2) 02 Split Test should split single page pdf into a new single page pdf files:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/User/WebDevelopment/test/pdftest/node_modules/pdf-extract/node_modules/mocha/lib/runnable.js:140:21)
      at Timer.listOnTimeout (timers.js:92:15)

  3) 03 Searchable Test should extract text from electronic searchable pdf:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/User/WebDevelopment/test/pdftest/node_modules/pdf-extract/node_modules/mocha/lib/runnable.js:140:21)
      at Timer.listOnTimeout (timers.js:92:15)

```

Also i would love to use this Module, im trying to split a PDF and then process the data within in, then save them into a DB. So this Module is literally perfect for what im trying to do, if i could get it to work.

**Comment by JBenedettini** [comment]
Will try getting it to work on my Ubuntu development server, will report back if its working there.

**Comment by JBenedettini** [comment]
Okay, strange enough following the exact same install practices and in the same express generated app, it works fine on my Ubuntu Dev machine. However on OSX ElCapitan i have the errors above. Not sure what it is causing the errors, il just continue to develop on the Ubuntu machine, probably better in the long run anyways!

**Comment by JBenedettini** [comment]
It seems its an issue with pdftk & El Capitan, and not pdf-extract, Issue here - http://stackoverflow.com/questions/32505951/pdftk-server-on-os-x-10-11 

So ive closed the issue here, thanks
