### ISSUE TITLE
no access to PATH in AWS Lambda

### ISSUE THREAD

**Issue by chrisdlangton** [nisaacson/pdf-extract#24]
As title suggests, you can't always get access to change the PATH, AWS Lambda is one of many that come to mind (CI's, AWS ECS, many PaaS, ect).

We need to be able to tell the library which binary to use, similar to this npm library offers, https://www.npmjs.com/package/pdf-text-extract

**Comment by jmaleonard** [comment]
We could package all the dependencies in the library then set the path on all functions explicitly?

**Comment by jmaleonard** [comment]
Something like 

`process.env['PATH'] = process.env['PATH'] + ':' + process.env['LAMBDA_TASK_ROOT'] + '/bin';
process.env['LD_LIBRARY_PATH'] = process.env['LAMBDA_TASK_ROOT'] + '/bin';`
